# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 288ec1ed91685f41652117fe002e5fc4abd51eee29de67472ab43cd0153e88b2bb749ef9a0d1e3132b4c286f858917546ad23b19a0ee16510164e63ce90daecf

test:
  secret_key_base: 4ae75d8cb3dbbb700b23d31add6d1095981248c8f71622ebbee149a1556e16af10fa29786662d224ad4a71cbb7c6598cc2d90773fbba503d23f80b096234b27c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
